POST http://localhost:8080/media?fileId=1.jpg
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJtYXJhdCIsInBhc3N3b3JkIjoiMTIzMzIxIn0.twYu50bfah6o43xpqfeuf4gsjEvfQ4A5C3xrTmxrSGk
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/*

< C:\\Users\marat\Desktop\1.jpg
--MfnBoundry--

###
http://localhost:8080/media?fileId=4c7bfca336517e8489a164b7ab379656