http://localhost:8080/user/5
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiY2FwdGlvbiI6Im1hcmF0IiwiZGVzY3JpcHRpb24iOiJxd2VydHkifQ.3b3fvIcNW0G_fwMQ7C79of70uy860cRPQXV7P4qFPNo
###

PUT http://localhost:8080/user
content-type: application/json
{
  "id": 1,
  "caption": "ping",
  "description": "pong"
}