GET http://localhost:8080/user
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjYXB0aW9uIjoibWFyYXQiLCJkZXNjcmlwdGlvbiI6Im5pY2UiLCJpZCI6IjEifQ.nYeybvPfTAXUtmqRFsroeQfF0ZrdKnzsXnctCPBCVSY
###

PUT http://localhost:8080/user
content-type: application/json
{
  "id": 1,
  "caption": "ping",
  "description": "pong"
}