http://localhost:8080/user/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NX0.LcsSrAyx2o5oQF8veOhzvBhhz9MfTASxF_Hatx2qUSk
###

PUT http://localhost:8080/user
content-type: application/json
{
  "id": 1,
  "caption": "ping",
  "description": "pong"
}